/**
* Avanxo Colombia
* @author 			Cristian Jose Mosquera Puello href = <cmosquera@avanxo.com>
* Project:			Terpel
* Description:		Classe que se encarga de representar los errores de validacion de webservices
*					
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					Description
*			-----	----------		--------------------	---------------
* @version	1.0		30/05/2017		Cristian Mosquera (CM)		Implementacion inicial de la excepcion.
**/
global class Ter_ValidationWsException extends Exception {

}