/**
* Avanxo Colombia
* @author 			Cristian Jose Mosquera Puello href=<cmosquera@avanxo.com>
* Project:			ProjectName
* Description:		Classe encargado de definir la excepciones de validacion de negocio.
*					
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					Description
*			-----	----------		--------------------	---------------
* @version	1.0		9/06/2017		Cristian Mosquera (CM)		Implementacion inicial de la excepcion.
**/
public class Ter_ValidationException extends Exception {

}