/***************************************************************************************************************
* Avanxo 
* @author           Juan David Uribe Ruiz
* Proyecto:         Fielo/Terpel
* Descripción:      Clase para identificar las excepciones de Encripcion AES
* Cambios (Version)
* -------------------------------------------
*           No.     Fecha           Autor                               Descripción
*           -----   ----------      ---------------------               ---------------
* @version   1.0    15/05/2017      Juan David Uribe Ruiz               Creación de la clase
****************************************************************************************************************/
public class Ter_AESException extends Exception{
    
}